[options]
db_host = False
db_port = False
db_user = odoo
db_password = odoo
db_name = odoo17
addons_path = C:\Users\ith\PycharmProjects\odoo17\odoo17\addons,
	C:\Users\ith\PycharmProjects\odoo17\odoo17\odoo\addons,
	C:\Users\ith\PycharmProjects\odoo17\custom_addons

bin_path = C:/Program Files/wkhtmltopdf/bin
wkhtmltopdf = C:/Program Files/wkhtmltopdf/bin/wkhtmltopdf.exe
admin_passwd = $pbkdf2-sha512$600000$o7SWEoLQuneuFQJgDAFgDA$xt.khEaW2Ckti0Pb0j2h8GmfVgluAY0zt7zbfQ4jj5rL7mmxBFE3kOPLXVHO01BhiD7PWpVm4ZIjENHmSBvS/w

